# used ssjdispatcher deployment spec as a base
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariner-deployment
spec:
  selector:
    # Only select pods based on the 'app' label
    matchLabels:
      app: mariner
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: mariner
        release: test
        netnolimit: "yes" # check
        public: "yes"
    spec:
      serviceAccountName: mariner-service-account
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - mariner
              topologyKey: "kubernetes.io/hostname"
      automountServiceAccountToken: true
      containers:
      - name: mariner
        image: "quay.io/cdis/mariner-server"
        livenessProbe:
          httpGet:
            path: /_status
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /_status
            port: 80
        imagePullPolicy: Always
        ports:
        - containerPort: 80
